const services=[{icon:'🏬',title:'Commerce général',text:'Approvisionnement, négoce et distribution de produits pour professionnels et particuliers.',tag:'Distribution'},{icon:'🌍',title:'Import-export',text:'Opérations internationales fluides, sourcing, coordination documentaire et acheminement.',tag:'International'},{icon:'🚚',title:'Transport routier',text:'Des solutions de transport fiables avec visibilité sur chaque étape de votre livraison.',tag:'Logistique'},{icon:'👥',title:'Intérim & recrutement',text:'Mise à disposition rapide de profils adaptés à vos besoins opérationnels.',tag:'Talents'},{icon:'💼',title:'Services intellectuels',text:'Conseil, études, assistance technique et accompagnement stratégique des entreprises.',tag:'Conseil'},{icon:'▦',title:'Multiservices',text:'Une offre flexible et centralisée pour simplifier vos projets et opérations courantes.',tag:'Sur mesure'}];
const products=[{id:1,name:'Ordinateur professionnel ProBook',category:'Informatique',price:529900,rating:4.9,color:'blue',icon:'💻',badge:'Populaire'},{id:2,name:'Fauteuil ergonomique Executive',category:'Bureau',price:189000,rating:4.8,color:'orange',icon:'🪑',badge:'Nouveau'},{id:3,name:'Groupe électrogène industriel',category:'Industriel',price:1290000,rating:4.7,color:'slate',icon:'⚙️',badge:'Pro'},{id:4,name:'Pack fournitures entreprise',category:'Fournitures',price:74900,rating:4.6,color:'green',icon:'📦',badge:'Pack'}];
const testimonials=[{quote:'VISLIMMO nous a permis de centraliser nos achats et nos livraisons avec une grande réactivité.',name:'Aminata D.',role:'Responsable administrative'},{quote:'Une équipe disponible, structurée et orientée solutions. Le suivi logistique est particulièrement rassurant.',name:'Moussa K.',role:'Directeur des opérations'},{quote:'Notre besoin en personnel temporaire a été traité rapidement, avec des profils immédiatement opérationnels.',name:'Sophie N.',role:'Responsable RH'}];
const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'XOF',maximumFractionDigits:0}).format(n);let cart=JSON.parse(localStorage.getItem('vislimmo-cart')||'[]'),wishlist=JSON.parse(localStorage.getItem('vislimmo-wishlist')||'[]'),testIndex=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function notify(t){const el=$('#toast');el.textContent='✓ '+t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
function renderServices(){$('#servicesGrid').innerHTML=services.map(s=>`<article class="service-card reveal"><div class="service-top"><i>${s.icon}</i><span class="tag">${s.tag}</span></div><h3>${s.title}</h3><p>${s.text}</p><a href="#contact">En savoir plus →</a></article>`).join('');observeReveals()}
function renderProducts(){const q=$('#searchInput').value.toLowerCase(),cat=$('#categoryFilter').value;const list=products.filter(p=>(cat==='Tous'||p.category===cat)&&p.name.toLowerCase().includes(q));$('#productsGrid').innerHTML=list.map(p=>`<article class="product"><div class="product-visual ${p.color}"><span class="badge">${p.badge}</span><button class="wish ${wishlist.includes(p.id)?'active':''}" data-wish="${p.id}">♥</button>${p.icon}</div><div class="product-body"><div class="product-meta"><span>${p.category}</span><span>⭐ ${p.rating}</span></div><h3>${p.name}</h3><div class="product-foot"><strong>${money(p.price)}</strong><button class="add-cart" data-add="${p.id}">+</button></div></div></article>`).join('');$$('[data-add]').forEach(b=>b.onclick=()=>addCart(+b.dataset.add));$$('[data-wish]').forEach(b=>b.onclick=()=>toggleWish(+b.dataset.wish))}
function toggleWish(id){wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];localStorage.setItem('vislimmo-wishlist',JSON.stringify(wishlist));renderProducts()}
function addCart(id){cart.push(products.find(p=>p.id===id));saveCart();notify('Produit ajouté au panier')}
function saveCart(){localStorage.setItem('vislimmo-cart',JSON.stringify(cart));renderCart()}
function renderCart(){$('#cartCount').textContent=cart.length;$('#cartTitleCount').textContent=cart.length;$('#cartItems').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-item"><span class="mini">${p.icon}</span><span><b>${p.name}</b><small>${money(p.price)}</small></span><button data-remove="${i}">×</button></div>`).join(''):'<div class="empty">🛍️<h3>Votre panier est vide</h3><p>Découvrez notre sélection de produits.</p></div>';$('#cartTotal').hidden=!cart.length;$('#totalPrice').textContent=money(cart.reduce((a,p)=>a+p.price,0));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart()})}
function openCart(open=true){$('#cart').classList.toggle('open',open);$('#overlay').classList.toggle('open',open);document.body.style.overflow=open?'hidden':''}
function showTest(){const t=testimonials[testIndex];$('#quote').textContent='“'+t.quote+'”';$('#person').textContent=t.name;$('#role').textContent=t.role}
function observeReveals(){const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(e=>obs.observe(e))}
renderServices();renderProducts();renderCart();showTest();observeReveals();
$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));$('#cartBtn').onclick=()=>openCart();$('#closeCart').onclick=()=>openCart(false);$('#overlay').onclick=()=>openCart(false);$('#searchInput').oninput=renderProducts;$('#categoryFilter').onchange=renderProducts;$('#prevTest').onclick=()=>{testIndex=(testIndex+testimonials.length-1)%testimonials.length;showTest()};$('#nextTest').onclick=()=>{testIndex=(testIndex+1)%testimonials.length;showTest()};$('#trackBtn').onclick=()=>{$('#trackResult').hidden=false};$('#checkout').onclick=()=>notify('Commande prête à être configurée');$$('.demo-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();notify('Formulaire enregistré en démonstration')});
window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;$('#progress').style.width=(scrollY/max*100)+'%'});
const statsObs=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting||e.target.dataset.done)return;e.target.dataset.done=1;const target=+e.target.dataset.count;let n=0;const step=Math.max(1,Math.ceil(target/55));const timer=setInterval(()=>{n=Math.min(target,n+step);e.target.textContent=n.toLocaleString('fr-FR');if(n===target)clearInterval(timer)},24)}),{threshold:.6});$$('[data-count]').forEach(e=>statsObs.observe(e));
